Time::DATE_FORMATS[:date] = "%d"
Time::DATE_FORMATS[:month_year] = "%B %Y"
Time::DATE_FORMATS[:day_of_week] = "%A"
Time::DATE_FORMATS[:stardate] = "%Y.%j"
Time::DATE_FORMATS[:stardatetime] = "%Y.%j.%H.%M.%S"
Time::DATE_FORMATS[:standard] = "%d %B %Y"
Time::DATE_FORMATS[:fullDT] = "%Y %m %d %H %M %S "